version: v1.0
name: Publish calico/base images
agent:
  machine:
    type: f1-standard-2
    os_image: ubuntu2204

execution_time_limit:
  minutes: 30

global_job_config:
  secrets:
    - name: docker-hub
  prologue:
    commands:
      - echo $DOCKERHUB_PASSWORD | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - checkout

blocks:
  - name: Publish calico/base images
    dependencies: []
    skip:
      when: "branch !~ '.+'"
    task:
      jobs:
        - name: Linux multi-arch
          commands:
            - if [ -z "${SEMAPHORE_GIT_PR_NUMBER}" ]; then make -C base push-all CONFIRM=true; fi

  - name: Push calico/base multi-arch manifests
    skip:
      when: "branch !~ '.+'"
    dependencies:
      - Publish calico/base images
    task:
      secrets:
        - name: docker
      jobs:
        - name: Linux multi-arch manifests
          commands:
            - if [ -z "${SEMAPHORE_GIT_PR_NUMBER}" ]; then make -C base push-manifest CONFIRM=true; fi
